---
development:
  UNSPLASH_ACCESS_KEY: <UNSPLASH_ACCESS_KEY>
  UNSPLASH_SECRET_KEY: <UNSPLASH_SECRET_KEY>
  GOOGLE_CREDS: '<GOOGLE_CREDS>'
test:
  UNSPLASH_ACCESS_KEY: <UNSPLASH_ACCESS_KEY>
  UNSPLASH_SECRET_KEY: <UNSPLASH_SECRET_KEY>
  GOOGLE_CREDS: '<GOOGLE_CREDS>'

production:
  UNSPLASH_ACCESS_KEY: <UNSPLASH_ACCESS_KEY>
  UNSPLASH_SECRET_KEY: <UNSPLASH_SECRET_KEY>
  GOOGLE_CREDS: '<GOOGLE_CREDS>'
